permalink:           pretty

# Setup
title:               'JekyllBook'
tagline:             'A Jekyll theme'
url:                 https://ebetica.github.io/jekyllbook/
baseurl:             '/jekyllbook'
homepage_title:      Home

# About/contact
author:
  name:              Zeming Lin
  url:               https://twitter.com/ebetica
github:
  repo:              https://github.com/ebetica/jekyllbook/

# Custom vars
version:             1.0.0

multilingual:        false
src:                 "."
default_theme:       "ayu"

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable : true

# Chapter Configuration (up to a 2 level nested list)

prologues:
  - path: chapters/prologue.md
    sections:
      - path: chapters/prologue2.md
chapters:
  - path: chapters/01.md
    sections:
      - path: chapters/01-1.md
      - path: chapters/01-2.md
  - path: chapters/02.md
epilogues:
  - path: chapters/epilogue.md
